# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bender < Formula
  desc "Spec-driven scaffold for Claude Code — bender CLI"
  homepage "https://github.com/mayckol/ai-bender"
  version "0.22.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mayckol/ai-bender/releases/download/v0.22.0/bender_v0.22.0_darwin-amd64.tar.gz"
      sha256 "0ecdc2488b9b1f2aa25a31150a11136ade1c60994fa5b73c98e4047987780ad3"

      define_method(:install) do
        bin.install "bender"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mayckol/ai-bender/releases/download/v0.22.0/bender_v0.22.0_darwin-arm64.tar.gz"
      sha256 "8b45ae66124da1bb4d50d9f8dd1caaa757494f0dc428aac570d4aa0482d05d86"

      define_method(:install) do
        bin.install "bender"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mayckol/ai-bender/releases/download/v0.22.0/bender_v0.22.0_linux-amd64.tar.gz"
      sha256 "ecf77241ed48996358cad0f620a4e9a404e1e110c4b8a1a1b25f66fbbb2b8582"
      define_method(:install) do
        bin.install "bender"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mayckol/ai-bender/releases/download/v0.22.0/bender_v0.22.0_linux-arm64.tar.gz"
      sha256 "4f785cc2c2ea5d5433b7a465b4a9a0279960986bc0bc7c363a395b28351e633a"
      define_method(:install) do
        bin.install "bender"
      end
    end
  end

  test do
    system "#{bin}/bender", "version"
  end
end
